version: "3"
services: 
  mysql-master:
    build:
      context: ./
      dockerfile: master/Dockerfile
    restart: always
    environment: 
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 13306:3306
    networks:
      mysql-replica-network:
        ipv4_address: 10.5.0.5
  mysql-slave:
    build:
      context: ./
      dockerfile: slave/Dockerfile
    restart: always
    environment: 
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 13307:3306
    volumes: 
      - ./slave/script:/script
    networks:
      mysql-replica-network:
        ipv4_address: 10.5.0.6
    depends_on: 
      - mysql-master
networks:
  mysql-replica-network:
networks: 
  mysql-replica-network:
    driver: bridge
    ipam: 
      config: 
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1